<script type="text/javascript">

</script>
<style type="text/css">

  /*.amount{display: none !important;}*/

</style>
<!-- <div class="product-top-column"> -->
<h3 id="heading" style=" margin-top: 15px; margin-bottom: 15px; "><?php echo $this->__('Product Reviews');?></h3>
	<div class="product-top seen-on-tv">

	<div class="reviews-column-left">

	<?php echo $this->getChildHtml('reviewtoolbar'); ?>
	<div id="reviewsdatares">
	 <?php echo $this->getChildHtml('responsivereviewdata'); ?>
	</div>

	</div>

	</div>

<!-- </div> -->



<style type="text/css">
/*.owl-item{
     width: 100px !important;
    
}*/
 img.tm_image {
    
    width: 70% !important;
}

 .sb-back-to-top{
            border-bottom: 1px solid #e5e5e5!important;
            border-top: 1px dashed #e5e5e5!important;
            padding-bottom: 10px!important;
            padding-top: 10px!important;
                line-height: 17px !important;
        }
    .sb-back-to-top > a {
        color: #58595b !important;
        cursor: pointer !important;
        font-size: 13px!important;
        text-decoration: none !important;
        background-position: 100% 65%!important;
        padding-left: 20px!important;
        padding-right: 20px!important;
        position: relative;
    }
    .sb-back-to-top span {
        font-size: 15px;
        font-weight: bold;
        line-height: 1.7;
        position: absolute;
        right: 0;
    }
    .sb-back-to-top > a:hover
    {
        color: #58595b !important;
    }
    #proresponsive .owl-item{width: 165px !important;} 

</style>
    <div id="headingsprom" style=" padding: 10px;"><h2><?php echo $this->__('People Also Liked'); ?></h2></div>
    <div id="proresponsive"  style="position: unset !important;">
   
    </div>

<script type="text/javascript">
  jQuery(document).ready(function() {

    
      jQuery("#proresponsive").owlCarousel({
        jsonPath : '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'yotporeviews/product.json';?>',
        jsonSuccess : customDataSuccess,
        scrollPerPage : false,
        items:2

      });
     
      function customDataSuccess(data){
        var content = "";
        var c=0;
        for(var i in data['response']["products"]){
         //console.log(i);
         
          if(c>=2){
            break;
          }
         
          if(data['response']["products"]!=''){
           var img = data['response']["products"][i].image;
           var url = data['response']["products"][i].url;
          // var alt = data['response']["products"][i].image_title;
           var total_review = data['response']["products"][i].total_review;
           var average_score = Math.ceil(data['response']["products"][i].average_score);
           var name = data['response']["products"][i].name;
             
           content += '<ul><li style="padding: 5px;"><div style="max-width:295px;" class="product-image-wrapper"><a style="padding: 10px !important;" class="product-image" title="'+name+'" href="'+url+'"> <img class="tm_image" alt="'+name+'" src="'+img+'" style="width:200px;height:150px;"> </a></div><h2 class=""><a style="font-size:12px" title="'+name+'" href="'+url+'">'+name+'</a></h2>';
           if(average_score=5){
             content +='<ul class="yotpo_stars_ul" style="padding:0px !important"><li><span style="font-size: 12px;" class="glyphicon glyphicon-star2" aria-hidden="true"><i aria-hidden="true" class="fa fa-star"></i></span></li><li><span style="font-size: 22px;" class="glyphicon glyphicon-star2" aria-hidden="true"><i aria-hidden="true" class="fa fa-star"></i></span></li><li><span style="font-size: 22px;" class="glyphicon glyphicon-star2" aria-hidden="true"><i aria-hidden="true" class="fa fa-star"></i></span></li><li><span style="font-size: 22px;" class="glyphicon glyphicon-star2" aria-hidden="true"><i aria-hidden="true" class="fa fa-star"></i></span></li><li><span style="font-size: 22px;" class="glyphicon glyphicon-star2" aria-hidden="true"><i aria-hidden="true" class="fa fa-star"></i></span></li><li style="color:#a6a6a6 !important;font-size:12px !important;font-family: arial;">('+total_review+')</li></ul>';     
            }
          
          content +='</li></ul>';
          
          }
          c++;
          //console.log(i);
          
             
        }

        jQuery("#proresponsive").html(content);
      }
     
    });

</script>
<div class="sb-back-to-top"><a onclick="Effect.ScrollTo('root-wrapper'); return false;" href="javascript:void(0)"><?php echo $this->__('Back to top');  ?><span>^</span></a></div>